import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

import ReactQueryProvider from "./react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navigation() {
  // only show navigation on non dashboard pages
  const isDashboard = false; // Replace with actual logic

  if (isDashboard) {
    return null;
  }

  return (
    <nav className="bg-gray-100">
      <div className="flex items-center justify-between mx-auto max-w-6xl px-4 py-4 sm:px-6 lg:px-8">
        <Link href="/" className="font-semibold">
          The Workshop
        </Link>

        <div className="space-x-4 text-sm">
          <Link href="/order" className="hover:text-gray-400">
            Get a quote
          </Link>
          <a href="#" className="hover:text-gray-400">
            About us
          </a>
        </div>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navigation />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
